# Default validation strategy: "batch" (one API call for all fields)
default_strategy: batch

# Perplexity API settings
perplexity_api_url: "https://api.perplexity.ai/chat/completions"
perplexity_model: "sonar-pro"

# Data file settings
data:
  input_csv: "data/seagent_data_mini.csv"
  output_csv_csv: "results/mini_results_batch.csv"
  output_csv_json: "results/mini_results_batch.json"
  
# (Optional) List fields you do NOT want to validate.
validation:
  fields_to_skip:
    - "Provider Name"

# Logging settings (set to DEBUG for verbose logging)
logging:
  level: "INFO"
