# Default validation strategy: "threaded" (one API call per field)
default_strategy: threaded

# Perplexity API settings
perplexity_api_url: "https://api.perplexity.ai/chat/completions"
perplexity_model: "sonar-pro"

# Data file settings
data:
  input_csv: "data/seagent_data_mini.csv"
  output_csv_csv: "results/mini_results_threaded.csv"
  output_csv_json: "results/mini_results_threaded.json"
  
# (Optional) List fields you do NOT want to validate.
validation:
  fields_to_skip:
    - "Provider Name"
    - "Validated?"
    - "Probability of validated"
    - "Source"

# Logging settings (set to DEBUG for verbose logging)
logging:
  level: "INFO"
