name: seagent
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - conda-content-trust
  - conda-libmamba-solver
  - conda==24.1.2
  - cpuonly
  - jupyterlab
  - matplotlib
  - numpy
  - pip
  - python.app
  - python=3.11
  - pytorch
  - scipy
  - setuptools
  - torchvision
  - wheel
  - pandas
  - pydantic
  - python-dotenv
  - streamlit
  - aiohttp

